# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    container_name: go
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
    ports:
      - "80:8080"
    depends_on:
      - "db"

volumes:
  dbdata: null # create the volume for persisting data.
